version: '3.9'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbdata/setup:/docker-entrypoint-initdb.d
      - ./dbdata/data:/var/lib/mysql
    environment:
      - datasource.dialect=MYSQL
      - datasource.url= jdbc:mysql://mysql:3306/lavagna
      - datasource.username=user
      - datasource.password=password
      - spring.profile.active= dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lavagna
      
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    
    

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy

      

  mynginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html           
      - ./src/main/webapp:/usr/share/nginx/html
    depends_on:
      - app
    

    
    

