version: '3.9'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbdata/setup:/docker-entrypoint-initdb.d
      - ./dbdata/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lavagna
      - MYSQL_CHARACTER_SET=utf8
      - MYSQL_COLLATION=utf8_bin

      
      
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    
    

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_DIALECT=MYSQL
      - DB_URL=jdbc:mysql://mysql:3306/lavagna?useSSL=false
      - DB_USER=root
      - DB_PASS=password
      - SPRING_PROFILE=dev

      

  mynginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html           
      - ./src/main/webapp:/usr/share/nginx/html
    depends_on:
      - app
    

    
    

